[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "c4e97fc13b244bcd4292cf050b5d01dc0e6360ad"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "d8fd0172b6bbb18dc77f5341b3d8de6e7778c73910a0dfc9ad3e6db0af7aae24"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "2b3164a497809573738c02c0b585640a55454c15"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "fe291d8f50c97154f9052e55f99b9aaafaf9629a22adc52b083d390e61267717"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "0ec095129b97058551e70b66df853320491d3af6"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "9081f66e4586f8f861795b74a1849eab954938e826db575c019d4862d0606e75"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "a0606fa201b160c25d1ab6248f9c3b830c6453df"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "69844609cecda5c9f27d69386d0cda3704f4c452bb0f99d4fc4f8847c65cffbc"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "e25202e9d192d24401c4e62c31a03807419d5fa2"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "60b5da89943710dd802c8a8e121400c245da7e9b2f5d9964a836b26bb86d752a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "7017e57106e7a11cff935b51ba46347a4ea541fc"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "6e760f0dd354b37bf12595798220ec403b4332182825fa7ed51dcf64a5b539ae"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "7398b2056223311156bd4eadfb33351d9aeab32e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "5b0ca2b8e79ee3a07079e5c51c79ad3619eba07cca2cb05fef6193f73c589420"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "0f2d044ecfe23a49fac0dba6c3e8cb822bc71a4e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "0d7b5a4d0ec18fc40c66f470f752d5166fe45d5e0ab53bbdf727a05340742c3e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "9fdfe17a0119a1a7d143be49a0592e1792615886"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "2c78a8ff0516904b8083677ddaea241a785f0b1df618f4949fa216aa76d69069"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "cb0ee6600fae776521e71a650114b3e6e72afe36"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "1bf932556fc88f29daaa981ed8b264bf9c1d5c12845102c677149b1f251d1d96"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "84468c4bbcb2b08c2823fba07e5ba75082661b0b"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "d7d79d1c6808abc5042d52fb66872475d9149d72569554943e2fcbdaab89c13c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "f2042c7d1532d4c73de9ff61f420ede573c45df1"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "01e80b59dd5eb76005131d0dcb6d355746fafc4607d24cd58666588f8351024d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "57eeb499e8756f198862981f519bbae7641794e9"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "228ed09d8e7873abd67f5943a72c0b2c4e269391b047bf118f512db18153b56c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "22472b7ec66eea1da24e4ddc4a73aafc7b2da87c"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "24d93d6c72d3b1ca396b612ba7c8855d6cdfce3ea243d2d710aa4000e3f15328"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "389b7539de1078136887eef30d1b26a41a02f69b"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "58a5480f97cbbdf30b8438bb4b4783227ad0034624b6aef2c63d02c029cb549f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "9d57b802015c74447eac591d080573da9c1437f9"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "5d99b9f8f63b4c8b76d4d3de8b3aaf95cf5df77ad40ac199ce197c611628535a"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "cdb3c98c74525ccd6d3fca6b4b54dc4f7d969822"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "d0cad895761b25f28f047ff225ed32fb8f00b608f60ddc9e3865abcbb6df40f8"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "341cb452dddb3c41e2c751f88077d41f2c2d2fed"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "92cf515ef436dcfc1ca26b7a9c45cc460cd53d497aa34c621b4dfa84baae906d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "ce079211aac810539c6964d0d05efcac93ad1ee6"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "e6bda34a379229929ff96e2b644c34eda5105f128319ee824b586e7c1395cb8b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "1d1697d59fd4aacf908b43271cc973d6e755853b"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "17365d7c85cc82270b369989861de961d978ba9cdffc14b80876c47db884929c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "befd704f25020073658b4fd501dc0b8fa1f6ce2f"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "70c09f99712a4cee0a08e55210c60583852de0fb565af8b50ee2c847caafb097"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "caed76d79201685770a6212fba27c5006ee98ea0"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "64b526d6da1747641654e01930687abf727170a9b0eb5d5ad53895a734c317ca"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.riscv64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "d9cb6f21c0ddb28f4b07d2ea8dda7039dab21cda"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "b2cdafa265d868dbfcd3874d7449a73e724abcb23741f426031d830ec378df12"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "c7ff95458ed37c662e71b450d822729ae2b0a9e0"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "7d272032b9c53ad30c06a6b84d30f1e744a0b959450e0e52ebb8bb4f5974c12f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "e7fd68bec6060619cc246f614da3afd9a76cf8d7"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "2db954f81446a324c484b1f6d1caedc162925a85da8008a842b78bc6d5ce4493"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "6e95c0106f4d44358dac96355a5c259f427a36da"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "aefef083ef90c55c64ff848b387260072bbbb1cf9c40f6377d1eac30259b1c68"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "774753fa912bd964dfd26444c291f48ecf6115b7"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "b71e79f42ce82fcb8b1d87476d8cdd09d61d2ae022487ce40f64df7ed45a7cff"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "d4b9bc9356da1e2403f19854c5f5070e0a188276"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "4679f553a80f1d525cf0a6a2c7af52fb5e29cd5f4870d83de5c70b98d0dc8fc4"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "b8e9cc666b6f1fc4ab49ed41da3bc86838d030c1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "8356bcfecaa2aa2bdad7683cb5119bf0feb894f8b4cd65ba9397681e29a6c84e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "8ad271fa7e7943e3892de77e06bbf048001d53b5"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "3428d94dc7221d234976ce88b22c63dfe0935f6f9c7b82f4808e77ad5c024d15"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "d71b40ac6ced6114916add9a7cb4421b331db8c1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "3fcf7686a66cd45831802c5b401891f297dbed8fd9e229185f3de10b14963be5"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "b3c4f3999376912bb7406a4c8bf8a9324e162fff"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f041e70b0e3701b6ae44aff8e01740ab494a82c1b9170ae58d43d7b1793565b2"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "9476db5c299c5a94c7eba63091f14c8f1fd283d2"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "73b6e053e064580b92a05595dd270a590eb39a2149c60eb21a8a74be824ed4c0"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "d82c22d7155f01d96b46b98dcfe3fef259c0c3c7"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "e87439f7f06cea8f7ede202e17dfdc877d4c187dc93fff32e789d4a38bcb8643"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "2422222f7ec880df39f908482b99f545ccdb956d"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "ce2db911865b3cb98876eee3cf68ebca2271386881ede2dd630d22e092176113"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "1084f9d9635e8dcb519483e5c27fc37141d6c271"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "17d8583f55b03035bec1a0b1dc8b2490035ed8e6de2dff48f5b14d5afad3d45d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "561f0367a5ad2a449cda58a7a4d51e5815fc1902"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "c807ac6b2e3e34ce3f9432179248b3d22c40aa38bf96e0a54f1b00fb7f0bb45b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "d8e25847bbb6eb4adb8b89d171009e3ac17d8a03"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "3daccf3785172eecb66a173ef4e9959940c5ee9ac6309ac34bea1b3e05455760"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.4+1/SCALAPACK.v2.2.4.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
