[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "5c6b3aa6bae07cde63bbba351ddbb1b8283fa8f7"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "989714050e4bf20a408c6305c61e77285dbcc7ed32c3ac80ac729bddcb603442"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "753141f488261d8f84a796346ed92d46beacb95e"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "6078141dad0f45b9b8122d3f7a46ff88313621a976b86abfb1b815f893b5bfd9"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "1d1dcc5f1f869deb438a47eb83b24a15d77d59ef"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "e9ce09c2edea64f6427c083addd59d4c9b0393c6f463d14018dc90c089ea7467"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "1998478fa1e28dfb187686efea67e854b54934e2"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "14b9c2baa7462269694217ed39902d02bc2acc3156ebc08312780518bdbd08d0"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "e0133cf81a9c1e4db048060eb5d047fd43ccbeb1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "32dc238b1a5148f227f3a0286970aaf2a8be0f89d65ccdc3cd70d3bebef59c22"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "c326eeae57c41685318b0f807b29fe5bd3600cb5"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f27833d56a20da2cf5b1d49f26f6cbb96364df77aee49edeb8d0c397c6985443"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "c26549e95c648a8ce93393d76725c63502dd673f"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "d8b2a7e9dbb4b8f100364ccc86bfc107b61ad28909214222decc0516e92df511"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "745ffd012b4b1fda41f5e25b445415b9913a5352"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "49f1a797e7bd2bbb8f43bb1f7b8fc9a297bef09416d4bb761124de0dcd221a56"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "8956c5361638a21d72c92ca76e22939151d5de75"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "ec3db42764d72659598f26cc96fe536683ced9fe66ae429f17f60781e6adb950"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "de5ade895bfa3571265acb00517138f4d265c7f3"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "da7053412ae6db4542ebc63c25b9db4bec3cf5dc1fe2afd3770dfbd7eba14cd1"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "9f273c15af8348616ed0d7521d176228c70f92ef"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f6ca981e231ddaa6bee651a225dac43fe2fe6d79beb43b4c03f57c7ec70fe7e1"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "a881f7903b0d2859fc76f98bb7fad46d8e7edb6e"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "4eac9c80aaf83ff57e6433477a81974aa499badbd6de2bb9b01e8603eeb3c604"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "017f0c8cb314d7f0609b707430e1a90e9dc206a6"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "28813055dc481ab40cf44568031a0f333a477cd7bc7fdf5db642699302ac36be"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "e1666b1abb3695e43f4c68521af04fc54677f6e0"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "e8ee836c9d8842b3829bee841406edcd70c4e820e9235f6fcca7e6e97128f696"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "57a0b848aad093be41fc39475b49f375901c297e"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "8fbfa8687bfea0c1ddfe643166bc435af80abc671d75876b7370a48e306041bc"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "25915aec2b964670feb875f12b25285ff025a5e6"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "07960c15f521362127d80a218ac1d789db33d8795fb4ebfb37af3cc9912df71c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "520fd62e2ee2bae5cfad37a8f1c9e01cbb249585"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "0d4be6018ce8d6035f7a97b22328ea01d193e24bc947f9cf153215ccb945d261"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.powerpc64le-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "3300ec6b68aa49ae148484a798eedbf71f61f0d1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f7d6f294b1d20837a5ba47154faa939cefa7db0bf861760ada94770194daf921"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "powerpc64le"
git-tree-sha1 = "be8e2c8db674f16120189791f49bd4c09b0386d1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "752d63a106608d55905e6f09a570a4fb6c835201123410697eb2d4e760db2da5"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.powerpc64le-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "7782d4003700391e120acd1b101ba4b269f3ceeb"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "3c75250790df7842d96562ad343bb100df99ee98890ba58421bbbc654970f419"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.riscv64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "6f3ca135f6a66109e63c4323da971587dca8e853"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "718344d31801a103d9bd1eb9839eac13c56e6d28aac42dc8e2ff45b7ab66d282"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.riscv64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "99bef599e5da2204cb32ba59eeae1e68e21fbc8c"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "8365fcb00d0ea546be8fc3d19ac5c666dd5f4a6945ad1907a78ef3f73d59b221"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.riscv64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "riscv64"
git-tree-sha1 = "243a1140163b03299d2514a5d741ab86673f056e"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "00bda037f92d7d6136c18b73f3ff02c2b3236e4a7ab791f0ba8f73dcc7a0c006"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.riscv64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "923aa8ae4438901b80aa96b18ccf016b48d043b7"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "1834877f322b6cae7b47601292b8b59f76ab3fa7c9fa724e1b6c73a7d294cc62"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-apple-darwin-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "f31c8dae0dead4b42fe41aebcd3a74ea3b3a205e"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "907e41b5d5ee55b69708535b03754dd06892c15a171f3dd83d2c282e26a46159"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "0b7e48ef4cfcf90afd848113311ba16ddcb0a92f"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "191ee7a726ad0e6ba879ad1bd218c6f15b753df508a34d0c6aaaaa761a69a3c9"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "ebd4208c7e53a0d78cbf062ea6c2c8490fca5466"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "ce416d81025e5bb32141dd6777ee0f762f0213d5e7cb4ca3c9aa9a6059dc75e7"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "32c6f5c30dbd6ec3836327c3fe028405322dd67b"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "42d8d9fabcb12e9a073006c5c63d7563efad56e9e3642864efd19551f4e75647"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-gnu-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "e0475001bf684cf2439984023eaa7c087a163348"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "9f7631c830fd6e736e0fb24ed008f7289944e6311b89ab061706fcdd18ca8d3f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "85bffb748e7f40405f2294454f15a7a4ee87d309"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "0afd232e20ede804116b3d441dca2403fbf5b4cfc66e6eb0b4e478f03ab8e8f2"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "c8a5c40028d975effbdf8fcf68bdae08d35e2cbc"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "79478290807add9e59b131aae7c427d0aff719cd37e9cb0ce0121b9e821fd819"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-gnu-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "546b4e3d7ab95c7868bc58e6defc412e495447ce"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "9e6ff96109db0e0f372e98fd3ca4de5ce75d9d6a48153aa5b2842103628a9069"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-musl-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "6a754b7806b0f2c1761fe6690e7d0f8950489fc3"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "4998983b637919ce08479104f533bfdef888f51774054b4cbc388308bb897790"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-musl-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "2fbc1b261d5b9ee9dee7e9c7acfa5a8f609a6249"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "a848a90ff9825c00d47935b579ad73119829b4b0b273ee965f17d13f3bfb7e46"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-linux-musl-libgfortran5-mpi+openmpi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "f155a0dfe54e07033de84997b0870edc99770c80"
libgfortran_version = "5.0.0"
mpi = "mpiabi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "9fc72712c00ac404019dbd401e36d797ab02303a60b33cc8a34315c1d534a560"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-unknown-freebsd-libgfortran5-mpi+mpiabi.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "c8fa8ecbf8ccb24b18cce8b49c786a174b29849f"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "41d60c1826e45efcc3c26532dfe45ba998c8dd6823d5ec04802838233fa8525d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "98b5958b6bdfd4f12be73213a51954ef93d6fd7b"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "d4204262f063f1d84271641d14ea1f2cc344c0fc2424e9ce023639b86183738b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "515ad1d66e5d94614f2819586b7c232a913b29da"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "7f5ef51ebcd49f0709ab5516330057acab63ab5223a194964f0f05bf4ff447b1"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.2.301+0/SCALAPACK.v2.2.301.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
