[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "d80a4a512c810a19ebaf6c4dd523f3e1aca5876b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "e79b4f19bd44f6a6754cd629789617ef2707f5facc640b8f6b25de866aec685f"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "7de52e69895ef2064f04829a3498e05bdf44ccd4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "00e9b38e8fd77148aeda21306e9139f026cfe0f976f8e0b26a7cecae4aa83cf8"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "4485c597c4372e79f3deaf1a5d5f4deff709f8c1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "105c0c6ba5b90df39a3d21685efcd347b986289be6f43959a9782cedcb12c543"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "a5ce1b2e9a674252e32d3c707e0ba5596b87dd86"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "aed10d6e87a00411103384bcbd1054afddd3a651fb838722aa8c425bb4911e5e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "b856139ae1377d0b7ddf2665cea0f0a2b98908c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "7f06fefce6d3cbcb9e2d8aa88e51e78e6b58efa13203e7a03c1f88f6d40bf822"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "fd85a65f3d9284956646702d645b180436abe0a3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "b6d9584e35967ee7d66eac25e3da099d313adf08f6df53fa4b561804f9b1f0d6"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "41d6dd49b8dce0f731c98a27e3aa67dc746b3aa9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "9c1be862ea83a67e434e153035d845ccd40575d75d4141bf211cac1203fe077e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "4815013c571786dbf2d1096ce602138dd7cf15dd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "2d0440ff15e90658c306c6551f352cb198167a1eae094f0fc52ebb78dbf39d1b"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "3cc1cf50db7ea7331d942e2ef8eda611facb0cb6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "d338064644fa89838fa70cb9dc67704d00e99f0855017aae6f888b81c4814a34"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "b6feb9caea58af9d3663fb3fedb79c097567b0be"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f1f03326e34aede8ce8f3137ae728dd2d9e9bcd3e2556517dc71a3081b574c34"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "91748b99a3b353387a13b7a92979d8b3cb7304a8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f8e5795acb9c7ee7bf501a7464cbbab0e108ee864ce3a113f1d0ff3e8c1bfcb9"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "0d2b8b56b3470b992a92c4e69729805de39803bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "01c991bc02a5c6d6db6b1c77a0327d63fc438f68f5f5eead3fbdac1143e735f2"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "72eafd9bde0499b280522270bed26d6ef2aee47c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "5344c38c128cc426cc5df4e4c46f23fdaeed35cf5063ae9ec347b8ef780e6d22"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "e42e0397a6c71da8ac5624b40d02f1287217605e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "ff0e3b028e8687b60787ed54c6149e4397d6e0703a7cc05569520316dcfb7fd6"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "4828444908f0b5726c116caa3f43b48b91c9494b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "1fce2f217794f9e1ea0cea65db1229dda9f1415c1ab80c3f8861039b291a5ee3"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "80a14ec03fa148a86f4c12f678149de24bfe4ad5"
libgfortran_version = "4.0.0"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "1b4907d0135aab98b31f32450883436a2f88b999ab5b5c50ce13a220bde8a2bd"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "21d3e826792adc9ab92f329ccf7e339e2d094d52"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "ee806176cace73bd2dd58b4e200ae03ee8d66bc230678beae8c626e860385718"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "96c86a0bce3cf0fa33ead8050afa108fe4a03af8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f9dc5d0e72c60b2a8058ef9e7fde558edf17c513fa2da9e13b8f5e0636f87d98"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "a728927a5a9d01e07b9b4d6020e8d8ad8ff588ba"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "6c7c7583b170b68125c493147a450ef7811cfc20b2a935b3494bead22c03f2b4"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "dffc58ac2bfa4cde8ef07fdaedf8d4b13a6ae3c0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "9e219925a098b50ac9c2c49894536293fe55fbd4ee052931bc14aa998172cb81"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "b8bb1f3602ba85e9f58284550c6d3a4ed5bed113"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SCALAPACK.download]]
    sha256 = "a9eb98d1eb4de193455cb13a346da5490d17df1e99b82136d018093479a1c605"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "0463facf16a69c1e54966d6b1ae67b294f55b0bf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "0b809610d02bdbcd9045d458c025cc1a6d2d52b89c9faba121ca568fb26b94e1"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "0a98a171e510984f0549f3712ebd5fa45942ea53"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "fb467b22c98eb7e50a0ef77a3f71531b36d4ad1d2b57f181a6d3f2fb86b13054"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "aarch64"
git-tree-sha1 = "bab2efcd243c24c2d6d0f81222be0354f4943a62"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "0a6fac339d08cdbc1b29de2ba153926b15c3037fbe01dafe3a6903bc61334289"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "i686"
git-tree-sha1 = "50c7bd4aacbb864c92a255caea08cb13bcb684cb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "43c747f51d2692198fce87c0dd3419be376138e1ea38dc446e02fd1c78126b1e"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "eb96a6bc80663502794eb53cdf1c55f729020c0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "73346cb77de5a67220ab8fefe12710003ed993bc7309bc7a1c2bb8faf31f2405"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "f6224d91f9b5c7b118373e216c0988c5274d2418"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "92ab7a3a44ebdb919136cc9ff5c97ed896e077c323c5121c63218b08e0d1afc6"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "687e6d595f99f0e25be6119e71eea6f61b295cb4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "ebac67c4d7a7280592c0c159a0dea825b056a3ae7e999e78825a4e5f950c8069"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[SCALAPACK]]
arch = "armv7l"
git-tree-sha1 = "0b773cca6804107df28eeca41a630c7f6aa1c128"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SCALAPACK.download]]
    sha256 = "f36ba8acec9f53b1c8ad2336d35cba21439ab1296c4f86d59a591a01458ea03d"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SCALAPACK]]
arch = "x86_64"
git-tree-sha1 = "4c4a6861970df9fdff650a9202510e101ab71138"
libgfortran_version = "3.0.0"
os = "macos"

    [[SCALAPACK.download]]
    sha256 = "5c6324a0a695af482ca61d61f7065ca0ac0b3c31c42bc9da269cb2e61379e60c"
    url = "https://github.com/JuliaBinaryWrappers/SCALAPACK_jll.jl/releases/download/SCALAPACK-v2.1.0+1/SCALAPACK.v2.1.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
