# Autogenerated wrapper script for SCALAPACK_jll for aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline
export libscalapack

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("SCALAPACK")
JLLWrappers.@declare_library_product(libscalapack, "libscalapack.so.2.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libscalapack,
        "lib/libscalapack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
