# Autogenerated wrapper script for SCALAPACK_jll for powerpc64le-linux-gnu-libgfortran5-mpi+mpiabi
export libscalapack

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using mpif_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("SCALAPACK")
JLLWrappers.@declare_library_product(libscalapack, "libscalapack.so.2.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, mpif_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libscalapack,
        "lib/libscalapack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
