# Autogenerated wrapper script for SCALAPACK_jll for x86_64-unknown-freebsd-libgfortran5-mpi+openmpi
export libscalapack

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("SCALAPACK")
JLLWrappers.@declare_library_product(libscalapack, "libscalapack.so.2.2")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libscalapack,
        "lib/libscalapack.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
